# Generated by Django 4.2.1 on 2023-07-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subunidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subunidade',
            old_name='om',
            new_name='OM',
        ),
    ]
