# Generated by Django 4.2.1 on 2023-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subunidades', '0002_rename_om_subunidade_om'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunidade',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='cmt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome completo do Comandante'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Nome por Extenso'),
        ),
    ]
