# Generated by Django 4.2.1 on 2023-11-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subunidades', '0004_alter_subunidade_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunidade',
            name='enc_mat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_encmat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='sgte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_sgte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='cmt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_cmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
