# Generated by Django 4.2.1 on 2023-11-20 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subunidades', '0005_subunidade_enc_mat_subunidade_sgte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunidade',
            name='acesso_encmat',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_encmat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='acesso_mil',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_mil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subunidade',
            name='acesso_sgte',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_sgte', to=settings.AUTH_USER_MODEL),
        ),
    ]
