# Generated by Django 4.2.1 on 2023-12-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_pessoa_nome_mae'),
        ('subunidades', '0006_subunidade_acesso_encmat_subunidade_acesso_mil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunidade',
            name='acesso_encmat',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_encmat', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='acesso_mil',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_mil', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='acesso_sgte',
            field=models.ManyToManyField(blank=True, related_name='su_acesso_sgte', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='cmt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_cmt', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='enc_mat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_encmat', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='subunidade',
            name='sgte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_sgte', to='pessoas.pessoa'),
        ),
    ]
