# Generated by Django 4.2.1 on 2023-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('titulo_eleitor', models.CharField(max_length=50)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('cat_cnh', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logadouro', models.CharField(max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250)),
                ('data_nasc', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(max_length=250)),
                ('situacao', models.CharField(choices=[('Pré-Cadastro', 'Pendente de Homologação'), ('Ativo', 'Ativo'), ('Arquivo', 'Excluído do Efetivo')], default='Pré-Cadastro', max_length=30)),
            ],
            options={
                'permissions': (('acesso', 'Usuario pode alterar'),),
            },
        ),
    ]
