# Generated by Django 4.2.1 on 2023-07-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
