# Generated by Django 4.2.1 on 2023-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_remove_documento_pessoa_remove_endereco_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='peso',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=2, null=True),
        ),
    ]
