# Generated by Django 4.2.1 on 2023-10-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoa_altura_pessoa_escolaridade_pessoa_religiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Fundamental Incompleto', max_length=60),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome do Banco')),
                ('agencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta Corrente')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco', to='pessoas.pessoa')),
            ],
        ),
    ]
