# Generated by Django 4.2.1 on 2023-10-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_pessoa_escolaridade_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banco', to='pessoas.pessoa', verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=8, null=True, verbose_name='Fator RH'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=2, null=True, verbose_name='Tipo Sanguíneo'),
        ),
    ]
