# Generated by Django 4.2.1 on 2023-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_banco_pessoa_alter_pessoa_fator_rh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
