# Generated by Django 4.2.1 on 2023-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='secao_eleitoral',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='zona_eleitoral',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
