# Generated by Django 4.2.1 on 2023-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_secao_eleitoral_documento_zona_eleitoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_primeira_habilitacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
