# Generated by Django 4.2.1 on 2023-11-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_data_primeira_habilitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira Habilitação'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='rg',
            field=models.CharField(max_length=15, verbose_name='RG'),
        ),
    ]
