# Generated by Django 4.2.1 on 2023-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cat_cnh',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Categoria da CNH'),
        ),
    ]
