# Generated by Django 4.2.1 on 2023-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_cat_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='secao_eleitoral',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='zona_eleitoral',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
