# Generated by Django 4.2.1 on 2023-11-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_documento_secao_eleitoral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cat_cnh',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cnh',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cpf',
            field=models.CharField(max_length=25, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='rg',
            field=models.CharField(max_length=25, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='secao_eleitoral',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='zona_eleitoral',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
