# Generated by Django 4.2.1 on 2023-11-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_banco_pessoa_alter_pessoa_fator_rh_and_more'),
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionarioum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_um', models.CharField(blank=True, choices=[('Com os pais', 'Com os pais'), ('Só com o pai', 'Só com o pai'), ('Só com a mãe', 'Só com a mãe'), ('Com avós', 'Com avós'), ('Sozinho', 'Sozinho'), ('Com cônjuge', 'Com cônjuge')], max_length=100, null=True)),
                ('pergunta_dois', models.CharField(blank=True, choices=[('Junto', 'Junto'), ('Perto', 'Perto'), ('Longe', 'Longe')], max_length=100, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionario_um', to='pessoas.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='CreatequestionarioumForm',
            fields=[
                ('questionarioum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionarios.questionarioum')),
            ],
            bases=('questionarios.questionarioum',),
        ),
        migrations.DeleteModel(
            name='Gabarito',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
