# Generated by Django 4.2.1 on 2023-11-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_questionarioum_createquestionarioumform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatequestionarioumForm',
        ),
    ]
