# Generated by Django 4.2.1 on 2023-11-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_banco_pessoa_alter_pessoa_fator_rh_and_more'),
        ('questionarios', '0004_alter_questionarioum_pergunta_dois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_cinco',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_dez',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_nove',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_oito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_quatro',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_seis',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_sete',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pergunta_tres',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionarioum',
            name='pergunta_dois',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionarioum',
            name='pergunta_um',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Questionariodois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_um', models.CharField(max_length=3)),
                ('pergunta_dois', models.CharField(max_length=3)),
                ('pergunta_tres', models.CharField(max_length=50)),
                ('pergunta_quatro', models.CharField(max_length=50)),
                ('pergunta_cinco', models.CharField(max_length=3)),
                ('pergunta_seis', models.CharField(max_length=50)),
                ('pergunta_sete', models.CharField(max_length=50)),
                ('pergunta_oito', models.CharField(max_length=3)),
                ('pergunta_nove', models.CharField(max_length=50)),
                ('pergunta_dez', models.CharField(max_length=3)),
                ('pergunta_onze', models.CharField(max_length=50)),
                ('pergunta_doze', models.CharField(max_length=3)),
                ('pergunta_treze', models.CharField(max_length=3)),
                ('pergunta_quatorze', models.CharField(max_length=3)),
                ('pergunta_quinze', models.CharField(max_length=3)),
                ('pergunta_dezesseis', models.CharField(max_length=3)),
                ('pergunta_dezessete', models.CharField(max_length=3)),
                ('pergunta_dezoito', models.CharField(max_length=3)),
                ('pergunta_dezenove', models.CharField(max_length=50)),
                ('pergunta_vinte', models.CharField(max_length=3)),
                ('pergunta_vinteum', models.CharField(max_length=3)),
                ('pergunta_vintedois', models.CharField(max_length=3)),
                ('pergunta_vintetres', models.CharField(max_length=50)),
                ('pergunta_vintequatro', models.CharField(max_length=3)),
                ('pergunta_vintecinco', models.CharField(max_length=3)),
                ('pergunta_vinteseis', models.CharField(max_length=3)),
                ('pergunta_vintesete', models.CharField(max_length=3)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionario_dois', to='pessoas.pessoa')),
            ],
        ),
    ]
