# Generated by Django 4.2.1 on 2023-11-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_banco_pessoa_alter_pessoa_fator_rh_and_more'),
        ('questionarios', '0006_alter_questionariodois_pergunta_nove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariodois',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='questionario_dois', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='questionariotres',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='questionario_tres', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='questionarioum',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='questionario_um', to='pessoas.pessoa'),
        ),
    ]
