# Generated by Django 4.2.1 on 2023-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0008_relatoriocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionariodois',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionariotres',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relatoriocs',
            name='obs_entrevistador',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Entrevistador'),
        ),
        migrations.AlterField(
            model_name='relatoriocs',
            name='obs_questionario',
            field=models.TextField(blank=True, null=True, verbose_name='Observações dos Questinários'),
        ),
    ]
