# Generated by Django 4.2.1 on 2023-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0009_questionariodois_pontos_questionariotres_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionariodois',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionariodois',
            name='parcial',
            field=models.CharField(choices=[('Sem Sugestão', 'Sem Sugestão'), ('Não deve Servir', 'Não deve Servir'), ('Pode Servir', 'Pode Servir'), ('Deve Servir', 'Deve Servir')], default='Sem Sugestão', max_length=50),
        ),
        migrations.AddField(
            model_name='questionariotres',
            name='obs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questionariotres',
            name='parcial',
            field=models.CharField(choices=[('Sem Sugestão', 'Sem Sugestão'), ('Não deve Servir', 'Não deve Servir'), ('Pode Servir', 'Pode Servir'), ('Deve Servir', 'Deve Servir')], default='Sem Sugestão', max_length=50),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionarioum',
            name='parcial',
            field=models.CharField(choices=[('Sem Sugestão', 'Sem Sugestão'), ('Não deve Servir', 'Não deve Servir'), ('Pode Servir', 'Pode Servir'), ('Deve Servir', 'Deve Servir')], default='Sem Sugestão', max_length=50),
        ),
        migrations.AlterField(
            model_name='relatoriocs',
            name='obs_questionario',
            field=models.TextField(default='Perguntas a serem feitas ao entrevistado:', verbose_name='Observações dos Questinários'),
        ),
    ]
