# Generated by Django 4.2.1 on 2023-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0010_questionariodois_obs_questionariodois_parcial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariodois',
            name='obs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questionarioum',
            name='obs',
            field=models.TextField(default=''),
        ),
    ]
