# Generated by Django 4.2.1 on 2023-11-18 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0019_alter_atributos_ranking_inicial'),
        ('questionarios', '0011_alter_questionariodois_obs_alter_questionarioum_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriocs',
            name='entrevistador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistador', to='militares.militar'),
        ),
    ]
