# Generated by Django 4.2.1 on 2023-07-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_fabricacao', models.IntegerField(default=2000)),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gas'), ('Óleo Diesel', 'OD'), ('Álcool', 'Álcool'), ('Gasolina e Álcool', 'Flex')], default='Óleo Diesel', max_length=25)),
                ('consumo', models.IntegerField(default=1)),
                ('patrimonio', models.CharField(blank=True, max_length=30, null=True)),
                ('troca_oleo', models.DateField(blank=True, null=True)),
                ('fabricacao_pneu', models.DateField(blank=True, null=True)),
                ('capacidade_combustivel', models.IntegerField(default=20)),
                ('capacidade_passageiro', models.IntegerField(default=2)),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregada', 'Descarregada')], default='Disponível', max_length=20)),
            ],
        ),
    ]
