# Generated by Django 4.2.1 on 2023-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='consumo',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
