# Generated by Django 4.2.1 on 2023-11-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subunidades', '0006_subunidade_acesso_encmat_subunidade_acesso_mil_and_more'),
        ('quarteis', '0006_quartel_acesso_s1_quartel_acesso_s2_and_more'),
        ('viaturas', '0003_viatura_subunidade_viatura_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='odometro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viatura',
            name='placa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=20)),
                ('codigo_virola', models.CharField(max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('subunidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municao', to='subunidades.subunidade')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municao', to='quarteis.quartel')),
            ],
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nr_serie', models.CharField(max_length=50, verbose_name='Número de série')),
                ('qtde_tiros', models.IntegerField(default=0, verbose_name='Quantidade de tiros')),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregada', 'Descarregada')], default='Disponível', max_length=20)),
                ('outros_nr_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('historico', models.TextField(blank=True, null=True)),
                ('aes', models.TextField(blank=True, null=True, verbose_name='Acessórios e Sobressalentes')),
                ('subunidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='subunidades.subunidade')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='quarteis.quartel')),
            ],
        ),
    ]
