# Generated by Django 4.2.1 on 2023-11-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subunidades', '0006_subunidade_acesso_encmat_subunidade_acesso_mil_and_more'),
        ('viaturas', '0005_armamento_classificacao_municao_classificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municao',
            name='subunidade',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='consumo',
        ),
        migrations.AddField(
            model_name='viatura',
            name='consumo_plan',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo para Planejamento'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='consumo_real',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo Real'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='subunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viatura', to='subunidades.subunidade'),
        ),
    ]
