# Generated by Django 4.2.1 on 2023-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0006_remove_municao_subunidade_remove_viatura_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municao',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viatura',
            name='classificacao',
            field=models.CharField(choices=[('Vtr 3/4 Ton', 'Vtr 3/4 Ton'), ('Vtr 5 Ton', 'Vtr 5 Ton'), ('Vtr 7 Ton', 'Vtr 7 Ton'), ('Vtr Bld', 'Vtr Bld'), ('Ambulância', 'Ambulância'), ('Vtr Adm', 'Vtr Adm'), ('Reboque Cistena', 'Reboque Cistena'), ('Vtr Cisterna', 'Vtr Cisterna'), ('Ônibus', 'Ônibus'), ('Cozinha de Campanha', 'Cozinha de Campanha'), ('Vtr Basculante', 'Vtr Basculante'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
    ]
