# Generated by Django 4.2.1 on 2023-12-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0007_municao_quantidade_viatura_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='classificacao',
            field=models.CharField(choices=[('Fuzil 7,62mm', 'Fuzil 7,62mm'), ('Pistola 9mm', 'Pistola 9mm'), ('Metralhadora MAG', 'Metralhadora MAG'), ('FAP', 'FAP'), ('FAC', 'FAC'), ('Metrlhadora .50', 'Metrlhadora .50'), ('Fuzil 5,56mm', 'Fuzil 5,56mm'), ('Espingarda 12', 'Espingarda 12'), ('Morteiro Pesado 120mm', 'Morteiro Pesado 120mm'), ('Obuseiro 105mm', 'Obuseiro 105mm'), ('Obuseiro 155mm', 'Obuseiro 155mm'), ('Faca', 'Faca'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='situacao',
            field=models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='situacao',
            field=models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsumoMun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('municao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo', to='viaturas.municao')),
            ],
        ),
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disparos', models.IntegerField(default=0, verbose_name='Disparos efetuados')),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20, verbose_name='Situação do Armamento')),
                ('alteracao', models.TextField(blank=True, null=True, verbose_name='Ocorrência observada')),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracao', to='viaturas.armamento')),
            ],
        ),
    ]
