# Generated by Django 4.2.1 on 2023-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0008_viatura_observacoes_alter_armamento_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomun',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Munição Consumida'),
        ),
    ]
