# Generated by Django 4.2.1 on 2024-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0010_remove_armamento_tipo_armamento_calibre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracao',
            name='data',
            field=models.DateField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumomun',
            name='data',
            field=models.DateField(auto_now=True),
            preserve_default=False,
        ),
    ]
