# Generated by Django 4.2.1 on 2023-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_delete_viatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='subunidade',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
