# Generated by Django 4.2.1 on 2023-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_subunidade_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acesso',
            field=models.CharField(choices=[('OM', 'OM'), ('SU', 'SU')], default='SU', max_length=30),
        ),
    ]
