# Generated by Django 4.2.1 on 2023-07-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='acesso',
            field=models.CharField(choices=[('OM', 'OM'), ('SU', 'SU'), ('básico', 'Acesso básico'), ('novo', 'Novo usuário')], default='novo', max_length=30),
        ),
    ]
