# Generated by Django 4.2.1 on 2023-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_numero_alter_usuario_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='acesso',
            field=models.CharField(choices=[('Estado Maior', 'EM'), ('Comandante', 'Cmt SU'), ('Sargenteante', 'Sgte SU'), ('básico', 'Acesso básico'), ('novo', 'Novo usuário')], default='novo', max_length=30),
        ),
    ]
