# Generated by Django 4.2.1 on 2023-10-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='unidade',
        ),
    ]
