# Generated by Django 4.2.1 on 2023-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abreviatura', models.CharField(max_length=40)),
                ('esc_sup', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abrv_esc_sup', models.CharField(help_text='Abreviatura do Esc Sup', max_length=40)),
                ('divisao', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abrv_divisao', models.CharField(help_text='Abreviatura da Divisão de Exército', max_length=40)),
                ('cmdo_mil_a', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abrv_cma', models.CharField(help_text='Abreviatura do Cmdo Mil A', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
    ]
