# Generated by Django 4.2.1 on 2023-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0002_quartel_nome_historico_alter_quartel_abrv_cma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartel',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='quartel',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True),
        ),
    ]
