# Generated by Django 4.2.1 on 2023-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0003_quartel_cidade_quartel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartel',
            name='cmt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome completo do Comandante'),
        ),
    ]
