# Generated by Django 4.2.1 on 2023-11-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarteis', '0004_quartel_cmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartel',
            name='s1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='s2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='s3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='s4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='cmt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_cmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
