# Generated by Django 4.2.1 on 2023-11-20 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarteis', '0005_quartel_s1_quartel_s2_quartel_s3_quartel_s4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartel',
            name='acesso_s1',
            field=models.ManyToManyField(blank=True, related_name='acesso_s1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='acesso_s2',
            field=models.ManyToManyField(blank=True, related_name='acesso_s2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='acesso_s3',
            field=models.ManyToManyField(blank=True, related_name='acesso_s3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartel',
            name='acesso_s4',
            field=models.ManyToManyField(blank=True, related_name='acesso_s4', to=settings.AUTH_USER_MODEL),
        ),
    ]
