# Generated by Django 4.2.1 on 2023-12-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_pessoa_nome_mae'),
        ('quarteis', '0007_quartel_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartel',
            name='acesso_s1',
            field=models.ManyToManyField(blank=True, related_name='acesso_s1', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='acesso_s2',
            field=models.ManyToManyField(blank=True, related_name='acesso_s2', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='acesso_s3',
            field=models.ManyToManyField(blank=True, related_name='acesso_s3', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='acesso_s4',
            field=models.ManyToManyField(blank=True, related_name='acesso_s4', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='cmt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_cmt', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='s1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s1', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='s2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s2', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='s3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s3', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='quartel',
            name='s4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartel_s4', to='pessoas.pessoa'),
        ),
    ]
