# Generated by Django 4.2.1 on 2023-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_pessoa_nome_mae'),
        ('quarteis', '0008_alter_quartel_acesso_s1_alter_quartel_acesso_s2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartel',
            name='oficiais',
            field=models.ManyToManyField(blank=True, related_name='oficiais', to='pessoas.pessoa'),
        ),
        migrations.AddField(
            model_name='quartel',
            name='quadros',
            field=models.ManyToManyField(blank=True, related_name='quadros', to='pessoas.pessoa'),
        ),
    ]
