# Generated by Django 4.2.1 on 2023-07-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('militares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='militar', to='pessoas.pessoa'),
        ),
        migrations.AddField(
            model_name='militar',
            name='qualificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mil_qualif', to='militares.qualificacao'),
        ),
    ]
