# Generated by Django 4.2.1 on 2023-07-11 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0002_quartel_nome_historico_alter_quartel_abrv_cma_and_more'),
        ('militares', '0003_alter_militar_subunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mil_om', to='quarteis.quartel'),
            preserve_default=False,
        ),
    ]
