# Generated by Django 4.2.1 on 2023-09-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0004_militar_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camaradagem', models.IntegerField(default=100)),
                ('iniciativa', models.IntegerField(default=100)),
                ('persistencia', models.IntegerField(default=100)),
                ('reponsabilidade', models.IntegerField(default=100)),
                ('coragem', models.IntegerField(default=100)),
                ('disciplina', models.IntegerField(default=100)),
                ('apresentacao', models.IntegerField(default=100)),
                ('dedicacao', models.IntegerField(default=100)),
                ('resistencia_fisica', models.IntegerField(default=100)),
                ('conhecimento_tecnico', models.IntegerField(default=100)),
                ('militar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='militares.militar')),
            ],
        ),
    ]
