# Generated by Django 4.2.1 on 2023-09-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0005_atributos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributos',
            old_name='reponsabilidade',
            new_name='responsabilidade',
        ),
    ]
