# Generated by Django 4.2.1 on 2023-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0006_rename_reponsabilidade_atributos_responsabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
