# Generated by Django 4.2.1 on 2023-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0007_observacao_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
