# Generated by Django 4.2.1 on 2023-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0010_remove_observacao_punicao_observacao_solucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('militar', models.ManyToManyField(related_name='destino', to='militares.militar')),
            ],
        ),
    ]
