# Generated by Django 4.2.1 on 2023-10-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0012_militar_is_present_remove_destino_militar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='in_force',
            field=models.BooleanField(default=True),
        ),
    ]
