# Generated by Django 4.2.1 on 2023-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0014_alter_destino_check_in_alter_destino_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='data_praca',
            field=models.DateField(blank=True, null=True),
        ),
    ]
