# Generated by Django 4.2.1 on 2023-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0016_alter_militar_posto_grad_alter_militar_subunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributos',
            name='ranking_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
