# Generated by Django 4.2.1 on 2023-11-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0017_atributos_ranking_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos',
            name='ranking_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
