# Generated by Django 4.2.1 on 2023-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0018_alter_atributos_ranking_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos',
            name='ranking_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
