# Generated by Django 4.2.1 on 2023-10-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone Residencial', max_length=20, null=True),
        ),
    ]
